# Use postgres/example user/password credentials
version: '3.1'

networks:
  backend:

services:

  postgresql:
    user: root
    container_name: postgresql
    image: postgres:15
    environment:
      POSTGRES_DB: "questionnaire"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../questionnaire-data:/var/lib/postgresql/data
    networks:
      - backend


  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgresql:5432/questionnaire
      FRONTEND: http://wedding-of-kiril-and-natalia.ru
      DDL_AUTO: update
      INIT_MODE: never
    restart: on-failure
    networks:
      - backend

#  frontend:
#    build: "./wedding-process"
#    container_name: frontend
#    ports:
#      - "80:80"