# Use postgres/example user/password credentials
version: '3.1'

services:

  postgresql:
    user: root
    container_name: postgresql
    image: postgres:15
    environment:
      POSTGRES_DB: "questionnaire"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgresql:5432/questionnaire


