server:
  port: 8080

frontend:
  endpoint: ${FRONTEND}

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver