server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: '${DB_URL : "jdbc:postgresql://localhost:5432/test"}'
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver