server:
  port: 8080

frontend:
  endpoint: ${FRONTEND}

spring:
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
  datasource:
    url: ${DB_URL}
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ${INIT_MODE}
      encoding: utf-8